#!/bin/sh

set -eu

if [ "$#" -ne 1 ]; then
    echo "usage: $0 PATH_TO_VERSO" >&2
    exit 2
fi

command -v curl >/dev/null 2>&1 || {
    echo "bootstrap verification requires curl" >&2
    exit 2
}
command -v python3 >/dev/null 2>&1 || {
    echo "bootstrap verification requires python3" >&2
    exit 2
}

binary=$1
case "$binary" in
    /*) ;;
    *) binary=$(CDPATH= cd -- "$(dirname -- "$binary")" && pwd)/$(basename -- "$binary") ;;
esac
script_directory=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
migrations_directory=$(CDPATH= cd -- "$script_directory/../migrations" && pwd)
temporary_directory=$(mktemp -d "${TMPDIR:-/tmp}/verso-bootstrap.XXXXXX")
server_pid=

cleanup() {
    if [ -n "${server_pid:-}" ] && kill -0 "$server_pid" 2>/dev/null; then
        kill -TERM "$server_pid" 2>/dev/null || true
        wait "$server_pid" 2>/dev/null || true
    fi
    rm -rf "$temporary_directory"
}
trap cleanup EXIT HUP INT TERM

fail() {
    echo "bootstrap verification failed: $*" >&2
    exit 1
}

assert_log_contains() {
    log_file=$1
    expected=$2
    grep -F "$expected" "$log_file" >/dev/null || fail "missing '$expected' in $log_file"
}

run_server() {
    case_directory=$1
    port=$2
    stdout_file=$3
    stderr_file=$4
    shutdown_signal=$5

    (
        cd "$case_directory"
        exec env \
            -i \
            "PATH=${PATH:-/usr/bin:/bin}" \
            VERSO_SERVER_PORT="$port" \
            VERSO_MIGRATIONS_PATH="$migrations_directory" \
            "$binary" serve >"$stdout_file" 2>"$stderr_file"
    ) &
    server_pid=$!

    ready=0
    response=
    attempt=0
    while [ "$attempt" -lt 100 ]; do
        if response=$(curl --fail --silent "http://127.0.0.1:$port/"); then
            ready=1
            break
        fi
        if ! kill -0 "$server_pid" 2>/dev/null; then
            break
        fi
        sleep 0.05
        attempt=$((attempt + 1))
    done

    [ "$ready" -eq 1 ] || {
        sed -n '1,120p' "$stderr_file" >&2 || true
        fail "server did not become ready"
    }
    [ "$response" = "Verso is running" ] || fail "unexpected HTTP response: $response"

    case "$shutdown_signal" in
        INT) kill -INT "$server_pid" ;;
        TERM) kill -TERM "$server_pid" ;;
        *) fail "unsupported shutdown signal: $shutdown_signal" ;;
    esac
    if wait "$server_pid"; then
        :
    else
        status=$?
        fail "server did not shut down cleanly (status $status)"
    fi
    server_pid=
}

free_port() {
    python3 -c 'import socket; s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()'
}

dump_directory="$temporary_directory/dump-default"
mkdir "$dump_directory"
(
    cd "$dump_directory"
    env -i "PATH=${PATH:-/usr/bin:/bin}" "$binary" config dump-default >default.toml 2>stderr.log
)
grep -F '# Starter configuration generated by' "$dump_directory/default.toml" >/dev/null || fail "default config was not written"
[ ! -e "$dump_directory/data" ] || fail "dump-default created runtime state"

default_directory="$temporary_directory/built-in-defaults"
mkdir "$default_directory"
run_server \
    "$default_directory" \
    "$(free_port)" \
    "$default_directory/stdout.log" \
    "$default_directory/stderr.log" \
    TERM
test -f "$default_directory/data/verso.db" || fail "default server did not create database"
test -d "$default_directory/data/assets" || fail "default server did not create asset directory"
test -d "$default_directory/data/cache" || fail "default server did not create cache directory"
assert_log_contains "$default_directory/stderr.log" 'event="server.starting"'
assert_log_contains "$default_directory/stderr.log" 'event="server.listening"'
assert_log_contains "$default_directory/stderr.log" 'event="http.request"'
assert_log_contains "$default_directory/stderr.log" 'event="server.shutdown"'

file_directory="$temporary_directory/file-backed"
mkdir "$file_directory"
printf '%s\n' \
    '[site]' \
    'name = "File-backed publication"' \
    '' \
    '[server]' \
    'host = "127.0.0.1"' \
    'port = 8080' \
    '' \
    '[database]' \
    'url = "state/database/verso.db"' \
    '' \
    '[migrations]' \
    'run_on_startup = false' \
    '' \
    '[storage.filesystem]' \
    'path = "state/assets"' \
    '' \
    '[cache]' \
    'path = "state/cache"' \
    >"$file_directory/verso.toml"
run_server \
    "$file_directory" \
    "$(free_port)" \
    "$file_directory/stdout.log" \
    "$file_directory/stderr.log" \
    INT
test -f "$file_directory/state/database/verso.db" || fail "file-backed server ignored database path"
test -d "$file_directory/state/assets" || fail "file-backed server ignored asset path"
test -d "$file_directory/state/cache" || fail "file-backed server ignored cache path"
if grep -F 'event="migrations.loaded"' "$file_directory/stderr.log" >/dev/null; then
    fail "file-backed server ran disabled startup migrations"
fi

invalid_directory="$temporary_directory/invalid-config"
mkdir "$invalid_directory"
printf '%s\n' '[server]' 'port = 0' >"$invalid_directory/verso.toml"
if (
    cd "$invalid_directory"
    env -i "PATH=${PATH:-/usr/bin:/bin}" "$binary" serve >stdout.log 2>stderr.log
); then
    fail "invalid configuration was accepted"
fi
assert_log_contains "$invalid_directory/stderr.log" 'event="configuration.failed"'

blocked_directory="$temporary_directory/blocked-path"
mkdir "$blocked_directory"
printf '%s\n' 'not a directory' >"$blocked_directory/blocked"
printf '%s\n' '[database]' 'url = "blocked/verso.db"' >"$blocked_directory/verso.toml"
if (
    cd "$blocked_directory"
    env -i "PATH=${PATH:-/usr/bin:/bin}" "$binary" serve >stdout.log 2>stderr.log
); then
    fail "unusable configured path was accepted"
fi
assert_log_contains "$blocked_directory/stderr.log" 'event="server.startup_failed"'
assert_log_contains "$blocked_directory/stderr.log" 'stage="directories"'

echo "bootstrap verification passed"
