import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "vite";

const workspaceRoot = dirname(fileURLToPath(import.meta.url));

function outputDirectory() {
  const args = process.argv.slice(2);
  const index = args.indexOf("--out-dir");
  if (index >= 0 && args[index + 1]) return resolve(args[index + 1]);
  const prefixed = args.find((arg) => arg.startsWith("--out-dir="));
  if (prefixed) return resolve(prefixed.slice("--out-dir=".length));
  return resolve(workspaceRoot, "dist");
}

const outDir = outputDirectory();
await mkdir(outDir, { recursive: true });
await build({
  configFile: resolve(workspaceRoot, "vite.config.ts"),
  build: { outDir },
});

const javascript = await readFile(resolve(outDir, "editor.js"));
const css = await readFile(resolve(outDir, "editor.css"));
if (javascript.length === 0 || css.length === 0) throw new Error("editor bundle is empty");

const modulePath = resolve(outDir, "editor_assets.zig");
await writeFile(modulePath, [
  "// Generated by web-editor/build.mjs; do not edit.",
  'pub const javascript = @embedFile("editor.js");',
  'pub const css = @embedFile("editor.css");',
  "",
].join("\n"));
