const std = @import("std");

pub const text =
    \\# Starter configuration generated by `verso config dump-default`.
    \\# Development derives the base URL from a loopback server address.
    \\# public_static_root = "./public"
    \\
    \\[runtime]
    \\environment = "development"
    \\
    \\[logging]
    \\format = "auto"
    \\omit_null_fields = true
    \\
    \\[site]
    \\name = "Verso"
    \\# base_url = "https://example.org"
    \\
    \\[server]
    \\host = "127.0.0.1"
    \\port = 8080
    \\
    \\[security]
    \\# Comma-separated peer addresses allowed to supply forwarded headers.
    \\trusted_proxy_addresses = ""
    \\
    \\[database]
    \\url = "./data/verso.db"
    \\
    \\[migrations]
    \\path = "migrations"
    \\run_on_startup = true
    \\
    \\[storage.filesystem]
    \\path = "./data/assets"
    \\
    \\[cache]
    \\path = "./data/cache"
    \\
    \\[ui]
    \\language = "en"
    \\theme = "default"
    \\# logo = "/assets/logo.svg"
    \\
    \\[features]
    \\math = true
    \\interactive_sections = false
    \\
    \\[mcp]
    \\enabled = true
    \\allow_publish = false
;

pub fn write(writer: *std.Io.Writer) !void {
    try writer.writeAll(text);
}
